[build] feature based builds . selectibve jre module

diff --git a/apps/mill-service/src/main/docker/base/Dockerfile b/apps/mill-service/src/main/docker/base/Dockerfile
--- a/apps/mill-service/src/main/docker/base/Dockerfile
+++ b/apps/mill-service/src/main/docker/base/Dockerfile
@@ -1,28 +1,41 @@
 FROM azul/zulu-openjdk:21-latest AS openjdk
 
+ARG APP_EDITION="basic"
+
 RUN apt update && \
-    apt install binutils -y && \
-      "$JAVA_HOME"/bin/jlink \
-         --verbose \
-         --add-modules ALL-MODULE-PATH \
-         --strip-debug \
-         --no-man-pages \
-         --no-header-files \
-         --compress=2 \
-         --output /customjre
+    apt install binutils -y
 
+RUN --mount=target=/mnt \
+        set -eux; \
+        modules_file=/mnt/build/jlink-modules/${APP_EDITION}/jlink-modules.txt; \
+        modules="ALL-MODULE-PATH"; \
+        if [ -f $modules_file ]; then \
+           echo "modules file exists"; \
+           modules=$(cat $modules_file);\
+        else \
+           echo "modules missing. fall back to ALL-MODULE-PATH"; \
+        fi ; \
+        echo "Selected modules $modules"; \
+        "$JAVA_HOME"/bin/jlink \
+          --add-modules "${modules}" \
+          --strip-debug \
+          --no-man-pages \
+          --no-header-files \
+          --compress=2 \
+          --output /customjre
 
-FROM debian:12-slim
+FROM debian:trixie-slim
 ENV JAVA_HOME=/jre
 ENV PATH="${JAVA_HOME}/bin:${PATH}"
 
+ARG APP_EDITION=basic
 # copy JRE from the base image
 COPY --from=openjdk --chown=1000:1000  /customjre $JAVA_HOME
 
 #end of base image
 
 ARG APPLICATION_USER=appuser
-RUN adduser --no-create-home --uid 1000 $APPLICATION_USER
+RUN useradd -u 1000 -M -s /usr/sbin/nologin $APPLICATION_USER
 
 # Configure working directory
 RUN mkdir -p /app/config && \
@@ -35,7 +48,7 @@ USER 1000
 EXPOSE 9090
 EXPOSE 8080
 
-COPY --chown=1000:1000 ./build/install/mill-service-boot/ /app/
+COPY --chown=1000:1000 ./build/install/mill-service-boot-${APP_EDITION}/ /app/
 
 RUN ln -s /config /app/config
 
